title: テスト
description: test
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
baseurl: ""  # GitHub Pagesでは通常空でOK
markdown: kramdown
permalink: pretty

# Optional: フィードバック用Issueリポジトリ（utterances用）
utterances:
  repo: your-org/docs-feedback
  issue-term: pathname
