name: ✍ 新しい記事を投稿
description: Markdown形式で新しい記事を作成します
title: "[記事] タイトルを記入してください"
labels: [投稿候補]

body:
  - type: input
    id: filename
    attributes:
      label: 📄 ファイル名（拡張子不要、英数字＋アンダーバーのみ）
      placeholder: 例）manual_test
    validations:
      required: true

  - type: input
    id: author
    attributes:
      label: 🖋 著者名
      placeholder: 例）PicricAcid
    validations:
      required: true

  - type: input
    id: tags
    attributes:
      label: 🏷 タグ（カンマ区切り）
      placeholder: 例）NeoVim, Lua
    validations:
      required: false

  - type: textarea
    id: content
    attributes:
      label: 📝 記事本文（Markdown）
      description: 改行・画像参照も含めて本文を記入してください
      placeholder: |
        ## はじめに
        本記事では...

        ![画像タイトル](https://example.com/image.png)
    validations:
      required: true
